# Generated by Django 4.2.7 on 2024-03-19 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="common.category",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="salary_exp",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
