# Generated by Django 4.2.7 on 2024-03-19 15:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("messanger", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="caption",
        ),
        migrations.RemoveField(
            model_name="image",
            name="caption",
        ),
    ]
